-- ScamShield AI+ database schema. Run in the Supabase SQL editor.
create extension if not exists pgcrypto;
create table public.analyses (id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,submission_type text not null check(submission_type in ('text','screenshot','link','qr','investment')),platform text,extracted_text text,submitted_url text,risk_score int not null check(risk_score between 0 and 100),risk_level text not null,predicted_category text,confidence numeric check(confidence between 0 and 100),created_at timestamptz not null default now());
create table public.risk_indicators (id uuid primary key default gen_random_uuid(),analysis_id uuid not null references public.analyses(id) on delete cascade,indicator_name text not null,explanation text,evidence_text text,score_added int not null default 0);
create table public.scam_patterns (id uuid primary key default gen_random_uuid(),category text not null,pattern_name text not null,description text,keywords text[] not null default '{}',recommended_actions text[] not null default '{}');
create table public.incident_reports (id uuid primary key default gen_random_uuid(),analysis_id uuid not null references public.analyses(id) on delete cascade,platform text,sender_details text,incident_date timestamptz,amount_lost numeric(12,2),transaction_details text,created_at timestamptz not null default now());
create table public.saved_analyses (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,analysis_id uuid not null references public.analyses(id) on delete cascade,created_at timestamptz not null default now(),unique(user_id,analysis_id));
alter table public.analyses enable row level security;alter table public.risk_indicators enable row level security;alter table public.scam_patterns enable row level security;alter table public.incident_reports enable row level security;alter table public.saved_analyses enable row level security;
create policy "users own analyses" on public.analyses for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "users read own indicators" on public.risk_indicators for select using(exists(select 1 from public.analyses a where a.id=analysis_id and a.user_id=auth.uid()));
create policy "patterns readable" on public.scam_patterns for select using(true);
create policy "users own reports" on public.incident_reports for all using(exists(select 1 from public.analyses a where a.id=analysis_id and a.user_id=auth.uid())) with check(exists(select 1 from public.analyses a where a.id=analysis_id and a.user_id=auth.uid()));
create policy "users own saved records" on public.saved_analyses for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
