"use client";
import {useMemo,useRef,useState} from "react";
import {FileImage,Link2,MessageSquareText,QrCode,TrendingUp,Trash2,UploadCloud} from "lucide-react";
import {useRouter} from "next/navigation";
import {ErrorState,SafetyDisclaimer} from "./ui";
import type {AnalysisResult} from "@/lib/types";
import {getNextSample,getSamplesByPlatform,samplePlatforms,type SamplePlatform,type ScamSample} from "@/lib/scam-samples";

const tabs=[["text","Paste Text",MessageSquareText],["screenshot","Upload Screenshot",FileImage],["link","Check Link",Link2],["qr","Scan QR Code",QrCode],["investment","Investment Offer",TrendingUp]] as const;
const steps=["Extracting content","Checking warning signs","Analysing scam patterns","Calculating risk score","Preparing recommendations"];

export function ScamInputTabs(){
 const[tab,setTab]=useState<string>("text"),[text,setText]=useState(""),[url,setUrl]=useState(""),[selectedPlatform,setSelectedPlatform]=useState<SamplePlatform>("SMS"),[selectedCategory,setSelectedCategory]=useState(""),[currentSampleIndex,setCurrentSampleIndex]=useState(-1),[activeSample,setActiveSample]=useState<ScamSample|null>(null),[busy,setBusy]=useState(false),[step,setStep]=useState(0),[error,setError]=useState(""),[preview,setPreview]=useState("");
 const input=useRef<HTMLInputElement>(null),router=useRouter();
 const platformSamples=useMemo(()=>getSamplesByPlatform(selectedPlatform),[selectedPlatform]);
 const filteredSamples=useMemo(()=>platformSamples.filter(x=>!selectedCategory||x.category===selectedCategory),[platformSamples,selectedCategory]);
 const categories=useMemo(()=>[...new Set(getSamplesByPlatform(selectedPlatform).map(x=>x.category))],[selectedPlatform]);

 function changePlatform(platform:SamplePlatform){if(activeSample)setText("");setSelectedPlatform(platform);setSelectedCategory("");setCurrentSampleIndex(-1);setActiveSample(null)}
 function loadNextSample(){const next=getNextSample(selectedPlatform,activeSample?.id);if(!next)return;setCurrentSampleIndex(platformSamples.findIndex(x=>x.id===next.id));setActiveSample(next);setSelectedCategory(next.category);setText(next.content);setError("")}
 function clearText(){setText("");setActiveSample(null);setSelectedCategory("");setCurrentSampleIndex(-1)}

 async function filePicked(file?:File){setError("");if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError("Unsupported file. Choose a JPG, PNG or WEBP image.");return}if(file.size>8*1024*1024){setError("The image is larger than the 8 MB limit.");return}setPreview(URL.createObjectURL(file));setBusy(true);try{if(tab==="screenshot"){setStep(0);const Tesseract=await import("tesseract.js");const out=await Tesseract.recognize(file,"eng");if(!out.data.text.trim())throw new Error("OCR could not find readable text.");setText(out.data.text)}else{const B=(window as any).BarcodeDetector;if(!B)throw new Error("QR scanning is not supported in this browser. Try Chrome or paste the destination into Check Link.");const bitmap=await createImageBitmap(file);const codes=await new B({formats:["qr_code"]}).detect(bitmap);if(!codes[0]?.rawValue)throw new Error("No QR code was detected. Try a clearer image.");setUrl(codes[0].rawValue)}}catch(e:unknown){setError(e instanceof Error?e.message:"Image processing failed.")}finally{setBusy(false)}}

 async function analyse(){setError("");if(tab==="investment"){router.push("/investment");return}if(!(text.trim()||url.trim())){setError("Add content to analyse first.");return}if(tab==="link"||tab==="qr"){try{new URL(url.startsWith("http")?url:`https://${url}`)}catch{setError("Enter a valid web address.");return}}setBusy(true);setStep(0);const progress=window.setInterval(()=>setStep(x=>Math.min(x+1,4)),1600);try{const response=await fetch("/api/analyse",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text,url,submissionType:tab,platform:selectedPlatform})});const data=await response.json();if(!response.ok)throw new Error(data.error||"The AI analysis could not be completed.");const result:AnalysisResult={...data,id:crypto.randomUUID(),submissionType:tab,platform:selectedPlatform,submittedText:text,submittedUrl:url,createdAt:new Date().toISOString()};sessionStorage.setItem(`analysis:${result.id}`,JSON.stringify(result));sessionStorage.setItem("latest-analysis",JSON.stringify(result));router.push(`/results/${result.id}`)}catch(e:unknown){setError(e instanceof Error?e.message:"Network error. Please retry.");setBusy(false)}finally{window.clearInterval(progress)}}

 return <div className="space-y-6">
  <div className="flex overflow-x-auto rounded-2xl border bg-white p-2">{tabs.map(([id,name,I])=><button key={id} disabled={busy} onClick={()=>{setTab(id);setError("")}} className={`flex min-w-max flex-1 items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${tab===id?"bg-navy text-white":"text-slate-600 hover:bg-slate-50"}`}><I size={18}/>{name}</button>)}</div>
  <div className="card p-6 md:p-8">
   {tab==="text"&&<>
    {activeSample&&<div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-sky-200 bg-sky-50 p-4"><div><b className="text-sky-900">Fictional testing sample</b><p className="mt-1 text-sm text-slate-600">Platform: {activeSample.platform} · Category: {activeSample.category} · Expected risk: {activeSample.expectedRisk}</p><p className="mt-1 text-xs text-slate-500">Sample {currentSampleIndex+1} of {getSamplesByPlatform(selectedPlatform).length}: {activeSample.title}</p></div><button className="text-sm font-bold text-brand hover:underline" onClick={loadNextSample}>Next sample →</button></div>}
    <label className="label" htmlFor="message">Suspicious message</label><textarea id="message" maxLength={12000} className="input min-h-56 resize-y" value={text} onChange={e=>{setText(e.target.value);if(activeSample&&e.target.value!==activeSample.content)setActiveSample(null)}} placeholder="Paste an SMS, WhatsApp, Telegram, email or social-media message…"/>
    <div className="mt-4 flex flex-wrap gap-3"><select aria-label="Message platform" className="input !w-auto" value={selectedPlatform} onChange={e=>changePlatform(e.target.value as SamplePlatform)}>{samplePlatforms.map(x=><option key={x}>{x}</option>)}</select><button className="btn-secondary" onClick={loadNextSample}>{activeSample?"Next sample":"Load fictional sample"}</button><button className="btn-secondary" onClick={clearText}><Trash2 size={17}/>Clear</button></div>
    <p className="mt-3 text-sm text-slate-500">Samples are fictional and provided for testing only. {filteredSamples.length} matching sample{filteredSamples.length===1?"":"s"}; available categories: {categories.join(", ")}.</p>
   </>}
   {(tab==="screenshot"||tab==="qr")&&<><button onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();filePicked(e.dataTransfer.files[0])}} className="w-full rounded-2xl border-2 border-dashed border-slate-300 p-10 text-center hover:border-sky-600"><UploadCloud className="mx-auto h-10 w-10 text-brand"/><b className="mt-4 block">Drop an image here or choose a file</b><span className="mt-2 block text-sm text-slate-500">JPG, PNG or WEBP · Maximum 8 MB</span></button><input ref={input} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>filePicked(e.target.files?.[0])}/>{preview&&<div className="mt-5 grid gap-5 md:grid-cols-2"><img src={preview} className="max-h-64 rounded-xl border object-contain" alt="Uploaded preview"/><div><label className="label">{tab==="qr"?"QR destination (never opened automatically)":"Extracted text preview"}</label>{tab==="qr"?<input className="input" value={url} onChange={e=>setUrl(e.target.value)}/>:<textarea className="input min-h-48" value={text} onChange={e=>setText(e.target.value)}/>}<button onClick={()=>{setPreview("");setText("");setUrl("")}} className="mt-3 text-sm font-bold text-red-700">Delete upload</button></div></div>}</>}
   {tab==="link"&&<><label className="label" htmlFor="url">Suspicious URL</label><input id="url" className="input" inputMode="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/path"/><p className="mt-3 text-sm text-slate-500">We inspect the URL text only and never visit it.</p></>}
   {tab==="investment"&&<div className="py-8 text-center"><TrendingUp className="mx-auto h-12 w-12 text-brand"/><h2 className="mt-4 text-2xl font-bold">Guided Investment Checker</h2><p className="mx-auto mt-2 max-w-lg text-slate-600">Review promised returns, payment methods, urgency and other red flags.</p></div>}
   {error&&<div className="mt-5"><ErrorState message={error}/></div>}
   {busy?<div className="mt-7" aria-live="polite"><div className="mb-2 flex justify-between text-sm font-bold"><span>{steps[step]}</span><span>{(step+1)*20}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-brand transition-all" style={{width:`${(step+1)*20}%`}}/></div></div>:<button onClick={analyse} className="btn-primary mt-7 w-full">{tab==="investment"?"Open Investment Checker":"Analyse for Scam Risk"}</button>}
  </div>
  <SafetyDisclaimer/><label className="flex items-start gap-3 text-sm text-slate-600"><input className="mt-1" type="checkbox"/> I consent to saving this analysis to my account (optional; sign-in required).</label>
 </div>
}
