"use client";
import Link from "next/link";import {AlertTriangle,CheckCircle2,ShieldAlert,Info,Phone,ExternalLink} from "lucide-react";import type {AnalysisResult,RiskLevel,WarningSign} from "@/lib/types";
export function RiskBadge({level}:{level:RiskLevel}){const c=level==="Low Risk"?"bg-emerald-100 text-emerald-800":level==="Suspicious"?"bg-amber-100 text-amber-800":"bg-red-100 text-red-800";return <span className={`inline-flex rounded-full px-3 py-1 text-sm font-bold ${c}`}>{level}</span>}
export function RiskScoreGauge({score,level}:{score:number;level:RiskLevel}){const color=score<30?"#059669":score<60?"#d97706":"#dc2626";return <div className="relative grid h-44 w-44 place-items-center rounded-full" style={{background:`conic-gradient(${color} ${score*3.6}deg,#e5e7eb 0)`}}><div className="grid h-36 w-36 place-items-center rounded-full bg-white text-center"><div><strong className="block text-5xl text-navy">{score}</strong><span className="text-sm text-slate-500">out of 100</span><div className="mt-2"><RiskBadge level={level}/></div></div></div></div>}
export function WarningSignCard({item}:{item:WarningSign}){return <article className="card p-5"><div className="flex justify-between gap-3"><AlertTriangle className={item.scoreContribution>0?"text-red-600":"text-emerald-600"}/><strong className={item.scoreContribution>0?"text-red-700":"text-emerald-700"}>{item.scoreContribution>0?"+":""}{item.scoreContribution}</strong></div><h3 className="mt-3 font-bold">{item.indicatorName}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.explanation}</p><p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><b>Evidence:</b> “{item.evidence}”</p></article>}
export function SafetyDisclaimer(){return <div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><Info className="shrink-0"/><p><b>Automated risk assessment:</b> ScamShield AI+ cannot guarantee that content is safe or fraudulent. Never share an OTP, password, full card number, Singpass password, seed phrase or private key. Verify using official channels.</p></div>}
export function RecommendedActions({actions}:{actions:string[]}){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{actions.map(a=><div className="card flex gap-3 p-4" key={a}><CheckCircle2 className="shrink-0 text-brand"/><b>{a}</b></div>)}</div>}
export function EmptyState({title="Nothing to show yet"}:{title?:string}){return <div className="card py-14 text-center"><ShieldAlert className="mx-auto mb-4 h-10 w-10 text-slate-400"/><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 text-slate-500">Add content and try again.</p></div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><b>We couldn’t complete the check.</b> {message} {retry&&<button className="ml-2 underline" onClick={retry}>Retry</button>}</div>}
export function HelpStrip(){return <div className="bg-navy py-10 text-white"><div className="container flex flex-col items-start justify-between gap-5 md:flex-row md:items-center"><div><h2 className="text-2xl font-bold text-white">Think you may have been scammed?</h2><p className="mt-1 text-slate-300">Contact your bank immediately, then call ScamShield at 1799.</p></div><div className="flex gap-3"><a className="btn bg-white text-navy" href="tel:1799"><Phone size={18}/>Call 1799</a><Link className="btn border border-white text-white" href="/help">Get help <ExternalLink size={16}/></Link></div></div></div>}
export function ResultView({result}:{result:AnalysisResult}){return <div className="space-y-10"><div className="card grid gap-8 p-6 md:grid-cols-[200px_1fr] md:p-9"><RiskScoreGauge score={result.riskScore} level={result.riskLevel}/><div><p className="eyebrow">Analysis complete</p><h1 className="mt-2 text-3xl font-bold">{result.scamCategory}</h1><p className="mt-3 max-w-2xl leading-7 text-slate-600">{result.summary}</p><div className="mt-5 flex flex-wrap gap-6 text-sm"><span><b>Confidence:</b> {result.confidence}%</span><span><b>Type:</b> {result.submissionType}</span><span><b>Platform:</b> {result.platform}</span></div></div></div><SafetyDisclaimer/><section><h2 className="mb-5 text-2xl font-bold">Detected warning signs</h2>{result.warningSigns.length?<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{result.warningSigns.map((w,i)=><WarningSignCard key={i} item={w}/>)}</div>:<EmptyState title="No common warning signs detected"/>}</section><section><h2 className="mb-5 text-2xl font-bold">What You Should Do Now</h2><RecommendedActions actions={result.recommendedActions}/></section><Link href={`/incident?id=${result.id}`} className="btn-primary">Prepare Incident Summary</Link></div>}
