export const samplePlatforms=["SMS","WhatsApp","Telegram","Email","Social media","Other"] as const;
export type SamplePlatform=(typeof samplePlatforms)[number];
export type ScamSample={id:string;platform:SamplePlatform;category:string;title:string;content:string;expectedRisk:"Moderate"|"High"|"Critical";redFlags:string[]};
const s=(id:string,platform:SamplePlatform,category:string,title:string,content:string,expectedRisk:ScamSample["expectedRisk"],redFlags:string[]):ScamSample=>({id,platform,category,title,content,expectedRisk,redFlags});
export const scamSamples:ScamSample[]=[
s("sms-bank","SMS","Bank phishing","Bank account suspension","DEMO BANK ALERT: Your account will be suspended today. Verify your password and security code at https://demo-bank.example/verify. Fictional test message.","Critical",["account threat","credentials","link"]),
s("sms-parcel","SMS","Fake parcel delivery","Missed parcel fee","FICTIONAL PARCEL: Delivery DEMO-4821 is held. Pay S$2.40 within 30 minutes at https://parcel-demo.example/fee to avoid return.","High",["fee","urgency","impersonation"]),
s("sms-otp","SMS","OTP request","Security code request","DemoPay: A transfer is pending. Reply with your one-time security code so our fictional support officer can cancel it immediately.","Critical",["OTP","urgency","fake support"]),
s("sms-gov","SMS","Government impersonation","Fictional penalty notice","FICTIONAL AGENCY: Ref GOV-DEMO-771 has an unpaid penalty. Pay today at https://agency-demo.example/notice or enforcement begins.","High",["authority","threat","payment"]),
s("sms-loan","SMS","Loan scam","Instant loan approval","QuickDemo Loans: S$20,000 pre-approved with no checks. Pay a S$180 release fee now. Call fictional +65 8000 0000.","High",["advance fee","unsolicited loan"]),
s("wa-family","WhatsApp","Impersonation scam","Family member asking for money","Hi Mum, new number—my phone broke. Can you transfer S$850 to my friend before 5pm? Please don't call, I'm in a meeting 🙏 Fictional chat.","High",["new number","transfer","no calls"]),
s("wa-job","WhatsApp","Job scam","Easy task job","Hello! Mia from Fictional Talent Hub 😊 Earn S$300 daily liking products. Pay a refundable S$50 activation deposit and start in 10 minutes.","High",["deposit","unrealistic earnings"]),
s("wa-market","WhatsApp","Marketplace scam","Buyer requests courier payment","I want your listing. I arranged DemoCourier. Pay S$35 insurance at https://courier-demo.example/claim, then your money is released. Fictional only.","High",["fake courier","seller fee"]),
s("wa-romance","WhatsApp","Romance scam","Emergency travel request","I feel so close to you ❤️ My fictional trip went wrong and my card is blocked. Send S$1,200 today and keep this between us.","High",["emotion","money","secrecy"]),
s("wa-tech","WhatsApp","Technical support scam","Remote support request","DemoTech Support: Your device has a virus. Install remote support from https://support-demo.example and share the connection password now.","Critical",["remote access","password"]),
s("tg-crypto","Telegram","Cryptocurrency scam","Guaranteed crypto signals","🚀 VIP CRYPTO SIGNAL\nOur fictional bot returned 18% this week. Deposit S$300; capital guaranteed. Contact @TradeMentorDemo in 30 minutes. https://crypto-demo.example Do not contact your bank.","Critical",["guarantee","pressure","payment"]),
s("tg-job","Telegram","Job scam","Paid review channel","DemoTasks SG: Earn S$180 today reviewing products. Send a S$60 top-up to unlock Task 1. Message @DemoTaskAdmin now.","High",["pay to work","unrealistic earnings"]),
s("tg-support","Telegram","Technical support scam","Fake wallet administrator","@DemoWalletAdmin: Your wallet is under review. Send your recovery phrase privately or connect at https://wallet-demo.example in 20 minutes. FICTIONAL.","Critical",["recovery phrase","fake admin"]),
s("tg-invest","Telegram","Investment scam","Managed trading pool","Demo Wealth Channel guarantees 12% weekly profit. Entry S$500. Four VIP slots remain—DM @TradeMentorDemo and transfer today.","Critical",["guarantee","scarcity"]),
s("tg-referral","Telegram","Cryptocurrency scam","Token referral bonus","FICTIONAL AIRDROP: Invite five friends and deposit S$100 to receive S$1,000 DemoCoin. Claim at https://token-demo.example before midnight.","High",["deposit","referrals"]),
s("email-bank","Email","Bank phishing","Account verification required","Subject: Immediate Account Verification Required\n\nDear Customer, DemoBank access will be suspended in 12 hours. Verify your username, password and security code at https://secure-demo-bank.example.\n\nFictional Security Department","Critical",["credentials","suspension"]),
s("email-invoice","Email","Fake invoice","Overdue supplier invoice","Subject: Final Notice—Invoice DEMO-1048\n\nAccounts Payable, open the fictional attachment Invoice-DEMO.pdf and pay S$4,820 to our new bank details today to avoid suspension.","High",["new bank details","attachment"]),
s("email-prize","Email","Fake prize","Award claim notification","Subject: You have been selected\n\nDemo Rewards International selected you for a fictional S$50,000 prize. Pay S$250 at https://rewards-demo.example/claim within 24 hours.","High",["prize","advance fee"]),
s("email-gov","Email","Government impersonation","Tax refund verification","Subject: Fictional Tax Refund Pending\n\nA S$780 refund awaits. Confirm your identity and banking password at https://agency-demo.example/refund. Ref GOV-DEMO-8802.","Critical",["authority","password"]),
s("email-mail","Email","Account suspension","Mailbox storage warning","Subject: Mailbox Deactivation\n\nYour DemoMail storage is full. Sign in at https://mail-demo.example/upgrade within one hour or messages will be deleted. Fictional notice.","High",["account threat","login"]),
s("social-prize","Social media","Fake prize","Brand giveaway winner","DM @DemoBrand_Prizes: 🎉 You won our fictional S$2,000 giveaway! Pay S$25 and enter card details at https://brand-demo.example/winner in 30 minutes.","Critical",["prize","card details"]),
s("social-recovery","Social media","Account suspension","Account recovery warning","DM @DemoPlatformSupport: Your account will be deleted. Send your password and verification code now so we can appeal. Fictional test.","Critical",["password","OTP"]),
s("social-invest","Social media","Impersonation scam","Influencer investment invitation","@FictionalCreatorBackup: Join my guaranteed crypto programme. Deposit S$400 at https://creator-demo.example before tonight.","High",["backup account","guarantee"]),
s("social-market","Social media","Marketplace scam","Reservation deposit","Marketplace DM: Many buyers want this fictional phone. Send S$120 to reserve it. No viewing or calls before payment.","High",["deposit","no viewing"]),
s("social-romance","Social media","Romance scam","Online friend in crisis","Private DM: We only met online, but I trust you. My fictional hospital bill is due today. Send S$900 and keep it secret ❤️","High",["rapid trust","secrecy"]),
s("other-call","Other","Government impersonation","Threatening phone call","Fictional call transcript: 'I am Officer Tan from the Demo Investigation Bureau. Transfer S$5,000 to a safety account now and tell nobody.'","Critical",["authority","safety account"]),
s("other-market","Other","Marketplace scam","Marketplace escrow chat","Fictional chat: 'Scan this replacement QR and pay S$45 to activate escrow now at https://market-demo.example.'","High",["QR payment","fake escrow"]),
s("other-support","Other","Technical support scam","Computer pop-up support","Fictional pop-up: CRITICAL VIRUS. Call +65 8000 0000 and give DemoSupport remote access plus your banking login.","Critical",["scare tactic","remote access"]),
s("other-invest","Other","Investment scam","Seminar investment pitch","Fictional seminar: DemoGrowth guarantees capital and 25% monthly returns. Transfer S$2,000 today before the invitation expires.","Critical",["guarantee","high return"]),
s("other-qr","Other","Payment scam","Replacement payment QR","Fictional notice: Official QR unavailable. Scan this replacement and send S$600 to DEMO MERCHANT immediately; no refunds.","High",["replacement QR","pressure"])
];
export const getSamplesByPlatform=(platform:SamplePlatform)=>scamSamples.filter(x=>x.platform===platform);
export const getSamplesByCategory=(category:string)=>category.trim()?scamSamples.filter(x=>x.category.toLowerCase()===category.trim().toLowerCase()):[];
export function getNextSample(platform:SamplePlatform,currentSampleId?:string|null){const matches=getSamplesByPlatform(platform);if(!matches.length)return undefined;const i=matches.findIndex(x=>x.id===currentSampleId);return matches[(i+1)%matches.length]}
export function getRandomSample(platform:SamplePlatform){const matches=getSamplesByPlatform(platform);return matches.length?matches[Math.floor(Math.random()*matches.length)]:undefined}
